---
title: More Real World Robotics
desc: Arjun Arlbert
slides: true
---
:slide_title Speaker: Arjun Ablbert

:image :300, :arjunalbert

:slide_title Topics

* What does Anduril do?
* What is interesting and complicated about it?
* How is the development team organized
* How do they use ROS
* What other tools
* What is your specific part in it
* How did you land that job
* Advice to students from your experiences
* Q&A


:lecture_end
