---
title: More Real World Robotics - and LAST CLASS!
desc: Last Class!
slides: true
---

:image :200, :adamring

:image :200, :arjunalbert

:image :200, :tomryden

:slide_title Speaker: Charles Squires

:image :200, :charliesquires

:slide_bigtitle Last Class is Today!

<blockquote class="pretty">Everybody! Thanks for your contribution to this course and all your hard work! You can see that you've achieved a lot and learned a lot! And especially thanks to our TAs!</blockquote>
