---
title: ROS Services
desc: Continuing with different ROS Nodes, visualizers and simulators
slides: true
---
## Logistics

* Checkin Questions
* Quiz (15 minutes) Command Line / Shell basics
* People's experiences with the cloud and docker desktops

## ROS Services

:topic_include :prr_ros_services

:slide_title Breakout

* Make sure you understand services
* Come up with two examples where services would make sense

:lecture_end