---
title: Robot Hardware
desc: How do our autonomous robots work?
slides: true
---
## Logistics (15 minutes)

Teams Are formed!

* Teams are basically study groups
* How to be an effective team mate
* We designed the teams to be balanced in their composition
* Everyone is still fully responsible for their own work (see :topic_link :academic_integrity )
* Still help each other out

:topic_include :prr_robot_hardware

:lecture_end