---
title: ROS From the top
desc: Looking at the key building blocks that we will be using
slides: true
---

**Reading: :topic_link :hw_119_chapters12**

**Reading: :topic_link :hw_119_chapters6**

*Reminder: Readings are your responsibility. You will be expected to come to class prepared, having read the material, and ready to participate in the discussion*

:slide_title Welcome

* :topic_link :cosi119a_grading
* Python Quiz

:topic_include :prr_ros_fundamentals

:lecture_end
