---
title: Robot Orientation
desc: The role of Maps in orientation and localization
slides: true
---
* **READING: [Particle Filters Explained Without Math](https://www.youtube.com/watch?v=aUkBa1zMKv4) **

*Reminder: "Readings" are your responsibility. You will be expected to come to class prepared, having read the material, and ready to participate in the discussion*

:topic_include :prr_building_maps

:slide_title References for further study


:lecture_end
