---
title: Mapping and Navigating
slides: true
desc: Deeper dive into Mapping and Navigating
---

:h2 Logistics
* Secret attendance code is: 
* Checkin Questions: and discussion
* Standups - Each Team
* Commentary on PAs

:topic_include :prr_localization

:topic_include :prr_navigating

:slide_title Demo with MiniRover

1. Show track
1. Show urdf
1. Show launch files and explain
1. Start mr_slam
1. Save map
1. Start mr_amcl
1. Discuss move_base

:lecture_end
